pkgmk: changes to make it work with openbsd's base

diff --git a/pkgmk b/pkgmk
--- a/pkgmk
+++ b/pkgmk
@@ -30,11 +30,21 @@ check() {
 }
 
 extract() {
-    # TODO: maybe consider using file?
+    # TODO: uncompress each common compress types
     log "extracting ${1}"
     case ${1} {
-    (*\.tar*) tar -x -f "${1}" -C "${SRC}" ;;
-    (*\.zip*) unzip -q "${1}" -d "${SRC}"  ;;
+    (*\.tar\.gz)
+        gunzip -d "${1}" -c | tar -x -f - -C "${SRC}"
+        ;;
+    (*\.tar\.bzip)
+        bzip -c "${1}" | tar -x -f - -C "${SRC}"
+        ;;
+    (*\.tar)
+        tar -x -f "${1}" -C "${SRC}"
+        ;;
+    (*\.zip)
+        unzip -q "${1}" -d "${SRC}"
+        ;;
     }
 }
 
@@ -49,10 +59,7 @@ handle_source() {
             i="${i##*/}"
         }
         [[ ! -f "${i}" ]] && die "${i} not present in build directory"
-        [[ "${i}" = *@(\.tar|\.zip)* ]] && {
-            extract "${i}"
-            continue
-        }
+        [[ "${i}" = *@(\.tar|\.zip)* ]] && extract "${i}"
         [[ -f "${i}" ]] && cp "${PKGMK_ROOT}/${i}" "${SRC}/${i}"
     }
 }
@@ -63,13 +70,13 @@ handle_md5sum() {
         local i
         for i in "${SRC}"/*; {
             [[ -f "${i}" ]] &&
-                md5sum "${i##*/}" >> "${PKGMK_ROOT}/md5sum"
+                md5 "${i##*/}" >> "${PKGMK_ROOT}/md5sum"
         }
     }
 
     [[ ! -f "${PKGMK_ROOT}/md5sum" ]] &&
         create_md5sum
-    md5sum --status -c "${PKGMK_ROOT}/md5sum" || die 'md5sum check failed' # FIX: GNU blob
+    md5 -c "${PKGMK_ROOT}/md5sum" || die 'md5sum check failed' # FIX: GNU blob
 
     unset -f create_md5sum
 }
@@ -82,27 +89,23 @@ mkpkg() {
 
     echo "${version}" > "${db}/version"
     echo "${USER}" > "${db}/owner"
+    echo "${depends[@]}" | tr ' ' '\n' > "${db}/depends"
 
-    touch "${db}/depends"
+    # remove ./ from the path
+    find . -type f -exec ksh -c 'printf "%s\n" {} | cut -c 3-' \; > "${db}/contents"
 
-    for i in ${depends[@]}; {
-        echo "${i}" >> "${db}/depends"
-    }
-
-    find . -type f -exec ksh -c "printf '%s\n' {} | cut -c 3-" \; > "${db}/contents"
-
-    tar -c -z -f "${PKGMK_ROOT}/${name}#${version}.pkg.tar.gz" .
+    tar -f - -c `< "${db}/contents"` | gzip > "${PKGMK_ROOT}/${name}#${version}.pkg.tar.gz"
     log 'package created'
 
     # these are nice to have
-    cp "${db}/"{version,owner,depends,contents} "${PKGMK_ROOT}"
+    cp "${db}/"{owner,contents} "${PKGMK_ROOT}"
 }
 
 usage() {
     cat << EOF
 usage: pkgmk [opts]
 opts:
-    -k  keep work directory
+    -w  keep work directory
     -h  print this help message
     -M  ignore md5sum checking
     -D  don't check dependencies
@@ -140,7 +143,7 @@ main() {
 }
 
 # TODO: move PKGTOOLS_DB to a sep file
-PKGTOOLS_DB="/var/lib/pkg"
+PKGTOOLS_DB='/var/lib/pkg'
 PKGMK_DOWNLOAD_PROG='wget'
 PKGMK_ROOT="${PWD}"
 PKGMK_WORK="${PKGMK_ROOT}/work"
